# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 16, 48, 27, 572769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 16, 48, 27, 572264, tzinfo=utc)),
        ),
    ]
