# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180223_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='validation_commentaire',
            new_name='approved_comment',
        ),
    ]
